### ISSUE TITLE
Update to work with Polymer 2

### ISSUE THREAD

**Issue by jgw96** [jifalops/app-toast#2]
Hey, very nice web component! Are you interested in updating this for polymer 2? Or possibly making it a hybrid component to work with both Polymer 1 and 2? I would definitely be interested in helping with this update in my free time if you are open to it.

**Comment by jifalops** [comment]
It should be hybrid compatible already. Are you having an issue with it?

**Comment by jifalops** [comment]
I mean early this week.

**Comment by jifalops** [comment]
A 2.0-preview branch is available but swipe does not work yet.

**Comment by jifalops** [comment]
@jgw96 The master branch is almost ready for the next release and includes polymer 2.0 and ES6 classes, but for some reason `this.$` is undefined whenever I click the show button in the demo. I don't believe that was true for the `2.0-preview` branch. Can you see if you get the same issue?

**Comment by jifalops** [comment]
Now uses Polymer 2.0.
